### ISSUE TITLE
[User story] The user has the ability to see the home page.

### ISSUE THREAD

**Issue by LeZderich** [CPNV-ES/MAW11_Mugiwaras_Looper#2]
# Description
As a user, I would like to see the home page 

# Acceptance criteria
- [x] The design is the same as the on exercice-looper (//TODO -> better in notion of done ?)
- [x] The links on the buttons link to the right place (//TODO -> be more specific

//given
A running php server

//when
access to your localhost root

//then
The homepage is showing and all the acceptance critera can be validated.

# Assets
http://exercice-looper.mycpnv.ch/
![image](https://github.com/CPNV-ES/MAW11_Mugiwaras_Looper/assets/135646622/2df6ceff-b9c0-47f0-95d6-000d3114f7b4)

**Comment by NicolasGlassey** [comment]
@LeZderich 

you'll find my feedback directly in the issue (//TODO)
